{
 "title": "SmartHome Devices",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Television Button",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\n.buttontv {\n  background-color: #b3ffd9;\n  border: none;\n  color: black;\n  padding: 15px 32px;\n  text-align: center;\n  text-decoration: none;\n  display: inline-block;\n  font-size: 16px;\n  margin: 4px 2px;\n  cursor: pointer;\n}\n\n</style>\n</head>\n<body>\n\n<center>\n  <h2>Television</h2>\n  <button class=\"buttontv\" onclick=\"tv_on()\"> Turn On Television</button>\n  <button class=\"buttontv\" onclick=\"tv_off()\"> Turn Off Television</button>\n</center>\n\n\n<script type=\"text/javascript\">\n\n   \n  function tv_on() {\n    var url = \"http://localhost:3001/tv_on\";\n    var data = new FormData();\n    data.append('parameter_1', 'value parameter 1');\n    var xhr = new XMLHttpRequest();\n    xhr.open(\"POST\", url, true);\n    xhr.setRequestHeader(\"Content-type\", \"application/x-www-form-urlencoded\");\n    xhr.send(data);\n  }\n\n\n  function tv_off() {\n    var url = \"http://localhost:3001/tv_off\";\n    var data = new FormData();\n    data.append('parameter_1', 'value parameter 1');\n    var xhr = new XMLHttpRequest();\n    xhr.open(\"POST\", url, true);\n    xhr.setRequestHeader(\"Content-type\", \"application/x-www-form-urlencoded\");\n    xhr.send(data);\n  }\n\n</script>\n\n</body>\n</html>\n"
   }
  },
  {
   "title": "Radio Button",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\n.buttontv {\n  background-color: #b3ffd9;\n  border: none;\n  color: black;\n  padding: 15px 32px;\n  text-align: center;\n  text-decoration: none;\n  display: inline-block;\n  font-size: 16px;\n  margin: 4px 2px;\n  cursor: pointer;\n}\n\n</style>\n</head>\n<body>\n\n<center>\n  <h2>Radio</h2>\n  <button class=\"buttontv\" onclick=\"radio_on()\"> Turn On Radio</button>\n  <button class=\"buttontv\" onclick=\"radio_off()\"> Turn Off Radio</button>\n</center>\n\n\n<script type=\"text/javascript\">\n\n   \n  function radio_on() {\n    var url = \"http://localhost:3001/radio_on\";\n    var data = new FormData();\n    data.append('parameter_1', 'value parameter 1');\n    var xhr = new XMLHttpRequest();\n    xhr.open(\"POST\", url, true);\n    xhr.setRequestHeader(\"Content-type\", \"application/x-www-form-urlencoded\");\n    xhr.send(data);\n  }\n\n\n  function radio_off() {\n    var url = \"http://localhost:3001/radio_off\";\n    var data = new FormData();\n    data.append('parameter_1', 'value parameter 1');\n    var xhr = new XMLHttpRequest();\n    xhr.open(\"POST\", url, true);\n    xhr.setRequestHeader(\"Content-type\", \"application/x-www-form-urlencoded\");\n    xhr.send(data);\n  }\n\n</script>\n\n</body>\n</html>\n"
   }
  },
  {
   "title": "Oven Button",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\n.button6 {\n  background-color: #3d0066;\n  border: none;\n  color: white;\n  padding: 15px 32px;\n  text-align: center;\n  text-decoration: none;\n  display: inline-block;\n  font-size: 16px;\n  margin: 4px 2px;\n  cursor: pointer;\n}\n\n</style>\n</head>\n<body>\n\n<center>\n  <h2>Oven</h2>\n  <button class=\"button6\" onclick=\"oven_on()\"> Turn On Oven</button>\n  <button class=\"button6\" onclick=\"oven_off()\"> Turn Off Oven</button>\n</center>\n\n\n<script type=\"text/javascript\">\n\n   \n  function oven_on() {\n    var url = \"http://localhost:3001/oven_on\";\n    var data = new FormData();\n    data.append('parameter_1', 'value parameter 1');\n    var xhr = new XMLHttpRequest();\n    xhr.open(\"POST\", url, true);\n    xhr.setRequestHeader(\"Content-type\", \"application/x-www-form-urlencoded\");\n    xhr.send(data);\n  }\n\n\n  function oven_off() {\n    var url = \"http://localhost:3001/oven_off\";\n    var data = new FormData();\n    data.append('parameter_1', 'value parameter 1');\n    var xhr = new XMLHttpRequest();\n    xhr.open(\"POST\", url, true);\n    xhr.setRequestHeader(\"Content-type\", \"application/x-www-form-urlencoded\");\n    xhr.send(data);\n  }\n\n</script>\n\n</body>\n</html>\n"
   }
  },
  {
   "title": "Coffee Maker Button",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\n.buttontv {\n  background-color: #b3ffd9;\n  border: none;\n  color: black;\n  padding: 15px 32px;\n  text-align: center;\n  text-decoration: none;\n  display: inline-block;\n  font-size: 16px;\n  margin: 4px 2px;\n  cursor: pointer;\n}\n\n</style>\n</head>\n<body>\n\n<center>\n  <h2>Coffee Maker</h2>\n  <button class=\"buttontv\" onclick=\"coffee_on()\"> Turn On Coffee Maker</button>\n  <button class=\"buttontv\" onclick=\"coffee_off()\"> Turn Off Coffee Maker</button>\n</center>\n\n\n<script type=\"text/javascript\">\n\n   \n  function coffee_on() {\n    var url = \"http://localhost:3001/coffee_on\";\n    var data = new FormData();\n    data.append('parameter_1', 'value parameter 1');\n    var xhr = new XMLHttpRequest();\n    xhr.open(\"POST\", url, true);\n    xhr.setRequestHeader(\"Content-type\", \"application/x-www-form-urlencoded\");\n    xhr.send(data);\n  }\n\n\n  function coffee_off() {\n    var url = \"http://localhost:3001/coffee_off\";\n    var data = new FormData();\n    data.append('parameter_1', 'value parameter 1');\n    var xhr = new XMLHttpRequest();\n    xhr.open(\"POST\", url, true);\n    xhr.setRequestHeader(\"Content-type\", \"application/x-www-form-urlencoded\");\n    xhr.send(data);\n  }\n\n</script>\n\n</body>\n</html>\n"
   }
  },
  {
   "title": "Oven",
   "type": "timeseries",
   "description": "Show when oven was on(1) anf off(0).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select time,state as oven_state\nfrom devices\nwhere device = 'oven'"
    },
    {
     "rawSql": "select time,state as present\nfrom present"
    }
   ]
  },
  {
   "title": "Radio",
   "type": "timeseries",
   "description": "Show when oven was on(1) anf off(0).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "select time,state as oven_state\nfrom devices\nwhere device = 'radio'"
    }
   ]
  },
  {
   "title": "Faucet",
   "type": "timeseries",
   "description": "Show when oven was on(1) anf off(0).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "select time,state as faucet_state\nfrom devices\nwhere device = 'faucet'"
    },
    {
     "rawSql": "select time,state as present\nfrom present"
    }
   ]
  },
  {
   "title": "Coffee Maker",
   "type": "timeseries",
   "description": "Show when oven was on(1) anf off(0).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "select time,state as oven_state\nfrom devices\nwhere device = 'coffee_maker'"
    },
    {
     "rawSql": "select time,state as present\nfrom present"
    }
   ]
  },
  {
   "title": "Television",
   "type": "timeseries",
   "description": "Show when oven was on(1) anf off(0).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "select time,state as oven_state\nfrom devices\nwhere device = 'tv'"
    }
   ]
  },
  {
   "title": "Fridgedoor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "rawSql": "select time,state\nfrom fridgedoor\n"
    }
   ]
  },
  {
   "title": "Doorbell",
   "type": "timeseries",
   "description": "Show when doorbell rang.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "rawSql": "select time,state\nfrom doorbell\n"
    }
   ]
  }
 ]
}