{
 "title": "SmartHome Gases",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "CO2",
   "type": "timeseries",
   "description": "Show values of CO2!",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select time,value as bedroom\nfrom gases\nwhere gas_type = 'CO2' and room = 'bedroom'\n"
    },
    {
     "rawSql": "select time,value as bathroom\nfrom gases\nwhere gas_type = 'CO2' and room = 'bathroom'\n"
    },
    {
     "rawSql": "select time,value as kitchen\nfrom gases\nwhere gas_type = 'CO2' and room = 'kitchen'\n\n"
    },
    {
     "rawSql": "select time,value as living_room\nfrom gases\nwhere gas_type = 'CO2' and room = 'living room'\n\n"
    },
    {
     "rawSql": "select time,value as garage\nfrom gases\nwhere gas_type = 'CO2' and room = 'garage'\n"
    },
    {
     "rawSql": "select time,value as balcony\nfrom gases\nwhere gas_type = 'CO2' and room = 'balcony'\n\n"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "bargauge",
   "description": "Show values of CO2!",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time,value as bedroom\nfrom gases\nwhere gas_type = 'CO2' and room = 'bedroom'\n"
    },
    {
     "rawSql": "select time,value as bathroom\nfrom gases\nwhere gas_type = 'CO2' and room = 'bathroom'\n"
    },
    {
     "rawSql": "select time,value as kitchen\nfrom gases\nwhere gas_type = 'CO2' and room = 'kitchen'\n\n"
    },
    {
     "rawSql": "select time,value as living_room\nfrom gases\nwhere gas_type = 'CO2' and room = 'living room'\n\n"
    },
    {
     "rawSql": "select time,value as garage\nfrom gases\nwhere gas_type = 'CO2' and room = 'garage'\n"
    },
    {
     "rawSql": "select time,value as balcony\nfrom gases\nwhere gas_type = 'CO2' and room = 'balcony'\n\n"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "description": "Show values of CO2!",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select time,value as bedroom\nfrom gases\nwhere gas_type = 'CO2' and room = 'bedroom'\n"
    },
    {
     "rawSql": "select time,value as bathroom\nfrom gases\nwhere gas_type = 'CO2' and room = 'bathroom'\n"
    },
    {
     "rawSql": "select time,value as kitchen\nfrom gases\nwhere gas_type = 'CO2' and room = 'kitchen'\n\n"
    },
    {
     "rawSql": "select time,value as living_room\nfrom gases\nwhere gas_type = 'CO2' and room = 'living room'\n\n"
    },
    {
     "rawSql": "select time,value as garage\nfrom gases\nwhere gas_type = 'CO2' and room = 'garage'\n"
    },
    {
     "rawSql": "select time,value as balcony\nfrom gases\nwhere gas_type = 'CO2' and room = 'balcony'\n\n"
    }
   ]
  },
  {
   "title": "Fire",
   "type": "timeseries",
   "description": "Show values of CO2!",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select time,value as bedroom\nfrom gases\nwhere gas_type = 'fire' and room = 'bedroom'\n"
    },
    {
     "rawSql": "select time,value as bathroom\nfrom gases\nwhere gas_type = 'fire' and room = 'bathroom'\n"
    },
    {
     "rawSql": "select time,value as kitchen\nfrom gases\nwhere gas_type = 'fire' and room = 'kitchen'\n\n"
    },
    {
     "rawSql": "select time,value as living_room\nfrom gases\nwhere gas_type = 'fire' and room = 'living room'\n\n"
    },
    {
     "rawSql": "select time,value as garage\nfrom gases\nwhere gas_type = 'fire' and room = 'garage'\n"
    },
    {
     "rawSql": "select time,value as balcony\nfrom gases\nwhere gas_type = 'fire' and room = 'balcony'\n\n"
    }
   ]
  },
  {
   "title": "Fire",
   "type": "timeseries",
   "description": "Show values of CO2!",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select time,value as bedroom\nfrom gases\nwhere gas_type = 'fire' and room = 'bedroom'\n"
    },
    {
     "rawSql": "select time,value as bathroom\nfrom gases\nwhere gas_type = 'fire' and room = 'bathroom'\n"
    },
    {
     "rawSql": "select time,value as kitchen\nfrom gases\nwhere gas_type = 'fire' and room = 'kitchen'\n\n"
    },
    {
     "rawSql": "select time,value as living_room\nfrom gases\nwhere gas_type = 'fire' and room = 'living room'\n\n"
    },
    {
     "rawSql": "select time,value as garage\nfrom gases\nwhere gas_type = 'fire' and room = 'garage'\n"
    },
    {
     "rawSql": "select time,value as balcony\nfrom gases\nwhere gas_type = 'fire' and room = 'balcony'\n\n"
    }
   ]
  },
  {
   "title": "Fire",
   "type": "state-timeline",
   "description": "Show values of CO2!",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "select time,value as bedroom\nfrom gases\nwhere gas_type = 'fire' and room = 'bedroom'\n"
    },
    {
     "rawSql": "select time,value as bathroom\nfrom gases\nwhere gas_type = 'fire' and room = 'bathroom'\n"
    },
    {
     "rawSql": "select time,value as kitchen\nfrom gases\nwhere gas_type = 'fire' and room = 'kitchen'\n\n"
    },
    {
     "rawSql": "select time,value as living_room\nfrom gases\nwhere gas_type = 'fire' and room = 'living room'\n\n"
    },
    {
     "rawSql": "select time,value as garage\nfrom gases\nwhere gas_type = 'fire' and room = 'garage'\n"
    },
    {
     "rawSql": "select time,value as balcony\nfrom gases\nwhere gas_type = 'fire' and room = 'balcony'\n\n"
    }
   ]
  },
  {
   "title": "CO",
   "type": "timeseries",
   "description": "Show values of CO2!",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "select time,value as bedroom\nfrom gases\nwhere gas_type = 'CO' and room = 'bedroom'\n"
    },
    {
     "rawSql": "select time,value as bathroom\nfrom gases\nwhere gas_type = 'CO' and room = 'bathroom'\n"
    },
    {
     "rawSql": "select time,value as kitchen\nfrom gases\nwhere gas_type = 'CO' and room = 'kitchen'\n\n"
    },
    {
     "rawSql": "select time,value as living_room\nfrom gases\nwhere gas_type = 'CO' and room = 'living room'\n\n"
    },
    {
     "rawSql": "select time,value as garage\nfrom gases\nwhere gas_type = 'CO' and room = 'garage'\n"
    },
    {
     "rawSql": "select time,value as balcony\nfrom gases\nwhere gas_type = 'CO' and room = 'balcony'\n\n"
    }
   ]
  },
  {
   "title": "CO",
   "type": "state-timeline",
   "description": "Show values of CO2!",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "select time,value as bedroom\nfrom gases\nwhere gas_type = 'CO' and room = 'bedroom'\n"
    },
    {
     "rawSql": "select time,value as bathroom\nfrom gases\nwhere gas_type = 'CO' and room = 'bathroom'\n"
    },
    {
     "rawSql": "select time,value as kitchen\nfrom gases\nwhere gas_type = 'CO' and room = 'kitchen'\n\n"
    },
    {
     "rawSql": "select time,value as living_room\nfrom gases\nwhere gas_type = 'CO' and room = 'living room'\n\n"
    },
    {
     "rawSql": "select time,value as garage\nfrom gases\nwhere gas_type = 'CO' and room = 'garage'\n"
    },
    {
     "rawSql": "select time,value as balcony\nfrom gases\nwhere gas_type = 'CO' and room = 'balcony'\n\n"
    }
   ]
  },
  {
   "title": "CO",
   "type": "timeseries",
   "description": "Show values of CO2!",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 32 },
   "targets": [
    {
     "rawSql": "select time,value as bedroom\nfrom gases\nwhere gas_type = 'CO' and room = 'bedroom'\n"
    },
    {
     "rawSql": "select time,value as bathroom\nfrom gases\nwhere gas_type = 'CO' and room = 'bathroom'\n"
    },
    {
     "rawSql": "select time,value as kitchen\nfrom gases\nwhere gas_type = 'CO' and room = 'kitchen'\n\n"
    },
    {
     "rawSql": "select time,value as living_room\nfrom gases\nwhere gas_type = 'CO' and room = 'living room'\n\n"
    },
    {
     "rawSql": "select time,value as garage\nfrom gases\nwhere gas_type = 'CO' and room = 'garage'\n"
    },
    {
     "rawSql": "select time,value as balcony\nfrom gases\nwhere gas_type = 'CO' and room = 'balcony'\n\n"
    }
   ]
  }
 ]
}